import{chromium}from'/home/lukee/.local/share/pnpm/global/5/.pnpm/playwright@1.59.1/node_modules/playwright/index.mjs';import fs from'node:fs';
const out=new URL('.',import.meta.url).pathname,b=await chromium.launch({executablePath:'/home/lukee/.cache/ms-playwright/chromium-1243/chrome-linux64/chrome',args:['--no-sandbox']});const results=[];
for(const width of[1440,390]){const p=await b.newPage({viewport:{width,height:width===390?844:900}}),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto('http://127.0.0.1:4370/');await p.waitForTimeout(4000);
for(const theme of['default','original']){await p.locator('app-theme-selector select:visible').selectOption(theme);await p.waitForTimeout(700);await p.screenshot({path:out+`root-${width}-${theme}.png`,fullPage:true});results.push({width,theme,graph:await p.evaluate(()=>{const el=document.querySelector('app-mempool-block-overview app-block-overview-graph');const c=window.ng?.getComponent(el);return c?{autofit:c.autofit,blockLimit:c.blockLimit,scale:c.scene?.vbytesPerUnit,tiles:Object.values(c.scene?.txs||{}).map(t=>({vsize:t.vsize,position:t.screenPosition})),sampleExtent:Object.values(c.scene?.txs||{}).reduce((s,t)=>s+t.vsize,0)}:null;}),errors:[...errors]});}
await p.route('**/api/v1/transaction-times?**',r=>r.fulfill({status:503,contentType:'application/json',body:'{"error":"controlled optional failure"}'}));
// Preserve the live address response, force its first real transaction into the pending
// state to exercise the optional timestamp path even if the reported tx confirmed.
await p.route('**/api/address/*/txs',async r=>{const response=await r.fetch();const data=await response.json();if(data.length)data[0].status={confirmed:false};await r.fulfill({response,json:data});});
await p.goto('http://127.0.0.1:4370/address/Xo5k9eY5Z9eYRYxfVuiVzSiZj4dJFmNvFC');await p.waitForTimeout(4000);const state=await p.evaluate(()=>{const c=window.ng.getComponent(document.querySelector('app-address'));return {error:c.error?.message||null,transactions:c.transactions?.length,pending:c.transactions?.filter(t=>!t.status.confirmed).length,loading:c.isLoadingTransactions};});results.push({width,controlledOptional503:state,errors:[...errors]});await p.screenshot({path:out+`address-optional503-${width}.png`,fullPage:true});await p.close();}
await b.close();fs.writeFileSync(out+'browser.json',JSON.stringify(results,null,2));console.log(JSON.stringify(results));
